format.version=1
model.family=PP-OCRv5

detector.file=ppocrv5_mobile_det.onnx
detector.sha256=A431985659DC921974177A95ADCFBB90FD9E51989A5E04D70D0B75F597B6E61D
detector.input.name=x
detector.input.rank=4
detector.output.name=fetch_name_0
detector.output.count=1
detector.output.rank=4

recognizer.file=ppocrv5_mobile_rec.onnx
recognizer.sha256=D8B4CA8F001FE3440337EC560B25E8BE4AA711B5BA1EDCFFF7F682E5501A8F70
recognizer.input.name=x
recognizer.input.rank=4
recognizer.input.fixed.height=48
recognizer.output.name=fetch_name_0
recognizer.output.count=1
recognizer.output.rank=3
recognizer.class.count=18385

dictionary.file=ppocrv5_mobile_rec_dict.txt
dictionary.sha256=D1979E9F794C464C0D2E0B70A7FE14DD978E9DC644C0E71F14158CDF8342AF1B
dictionary.charset=UTF-8
dictionary.entry.count=18383

recognizer.blank.token.count=1
recognizer.additional.special.token.count=1
recognizer.ctc.blank.index=0
